### ISSUE TITLE
embedTimeSeriesInMatrix issue

### ISSUE THREAD

**Issue by etrautmann** [djoshea/trial-data#4]
commit 14ee38d  "getValidTimeExtends...." from feb 7th introduces an issue that causes the following code to fail on Rig1 behavioral data:

tdca = TrialDataConditionAlign(td);
tdca = tdca.groupBy('conditionId')
tdca = tdca.align('GoCue -50 : GoCue + 600');
tdca.plotAnalogGroupedEachTrial2D('handX', 'handY')
 

with error:

Assignment has more non-singleton rhs dimensions than non-singleton
subscripts

Error in TrialDataUtilities.Data.embedTimeseriesInMatrix (line 123)
                    mat(i, indStart(i,c), c) = dataCell{i, c};

Error in TrialDataConditionAlign/getMultiAnalogAsMatrix (line 1571)
            data =
            TrialDataUtilities.Data.embedTimeseriesInMatrix(dataCell,
            timeCell, 'tvec', tvec);

Error in TrialDataConditionAlign/getMultiAnalogAsMatrixGrouped (line 1614)
            [data, tvec] = td.getMultiAnalogAsMatrix(nameCell,
            varargin{:});

Error in TrialDataConditionAlign/plotAnalogGroupedEachTrial2D (line 3758)
            [dataCell, tvec] = td.getMultiAnalogAsMatrixGrouped({name1,
            name2}, p.Results);

**Comment by djoshea** [comment]
Yup, I'll push the fix.
