### ISSUE TITLE
minor but in TrialDataConditionAlign  - plotProvidedAnalogDataGroupedEachTrial()

### ISSUE THREAD

**Issue by etrautmann** [djoshea/trial-data#7]
pulled changes this morning and existing plotting code broke, but this looks like simple typo in a recent commit:

Line 5114:      

p.Results.showMarksOnAxis      -> (should be)     p.Results.markShowOnAxis

**Comment by djoshea** [comment]
Whoops, sorry. Fixed in 799120866bce4d97b2bd40d14c66c0303fd3e5e5
